### ISSUE TITLE
Ruby style functions

### ISSUE THREAD

**Issue by RuBAN-GT** [seiya/ruby-mpi#2]
Good day! Thanks to the author for the work, but can you create wiki page with **ruby** mpi functions? 
For example, It is not clear how to use "MPI::Comm::WORLD.Bcast"

**Comment by seiya** [comment]
Hi,
I added sample codes to the ["implemented functions"](https://github.com/seiya/ruby-mpi/wiki/Implemented-functions) page.

Is it clear enough?

**Comment by RuBAN-GT** [comment]
Thank you very much!
